package fr.dossierfacile.common.enums;

public enum LogType {

    ACCOUNT_CREATED,
    ACCOUNT_CREATED_VIA_KC,
    ACCOUNT_LINK, // first connection on DF
    APPLICATION_TYPE_CHANGED,
    ACCOUNT_COMPLETED,
    ACCOUNT_DENIED,
    ACCOUNT_EDITED,
    ACCOUNT_VALIDATED,
    ACCOUNT_COMPLETE,
    ACCOUNT_MODIFICATION,
    ACCOUNT_DELETE,
    ACCOUNT_ARCHIVED,
    ACCOUNT_RETURNED,
    EMAIL_ACCOUNT_VALIDATED,
    FIRST_ACCOUNT_WARNING_FOR_DOCUMENT_DELETION,
    SECOND_ACCOUNT_WARNING_FOR_DOCUMENT_DELETION,
    DOCUMENT_DELETION_AFTER_2_ACCOUNT_WARNINGS,
    DO_NOT_ARCHIVE,
    FC_ACCOUNT_CREATION,
    FC_ACCOUNT_LINK,
    PARTNER_ACCESS_REVOKED,
    ZIP_DOWNLOAD,
    OPERATOR_COMMENT

}
