package fr.dossierfacile.common.enums;

public enum OwnerLogType {
    ACCOUNT_CREATED,
    ACCOUNT_CREATED_VIA_KC,
    ACCOUNT_CONFIRMED,
    ACCOUNT_DELETED,
    FIRST_ACCOUNT_WARNING_FOR_DELETION,
    SECOND_ACCOUNT_WARNING_FOR_DELETION,
    PROPERTY_CREATED,
    PROPERTY_COMPLETED,
    PROPERTY_DELETED;
}