package fr.dossierfacile.process.file.barcode.twoddoc.parsing;

import lombok.Getter;

@Getter
public enum TwoDDocDataType {

    ID_01("01", 0, -1, "Identifiant unique du document"),
    ID_02("02", 0, -1, "Catégorie de document"),
    ID_03("03", 0, -1, "Sous-catégorie de document"),
    ID_04("04", 0, -1, "Application de composition"),
    ID_05("05", 0, -1, "Version de l’application de composition"),
    ID_06("06", 6, 6, "Date de l’association entre le document et le code 2D-Doc"),
    ID_07("07", 6, 6, "Heure de l’association entre le document et le code 2D-Doc"),
    ID_08("08", 4, 4, "Date d’expiration du document"),
    ID_09("09", 4, 4, "Nombre de page du document"),
    ID_0A("0A", 9, 9, "Editeur du 2D-Doc"),
    ID_0B("0B", 9, 9, "Intégrateur du 2D-Doc"),
    ID_0C("0C", 0, -1, "URL du document"),
    ID_10("10", 0, 38, "Ligne 1 de la norme adresse postale du bénéficiaire de la prestation"),
    ID_11("11", 0, 38, "Qualité et/ou titre de la personne bénéficiaire de la prestation"),
    ID_12("12", 0, 38, "Prénom de la personne bénéficiaire de la prestation"),
    ID_13("13", 0, 38, "Nom de la personne bénéficiaire de la prestation"),
    ID_14("14", 0, 38, "Ligne 1 de la norme adresse postale du destinataire de la facture"),
    ID_15("15", 0, 38, "Qualité et/ou titre de la personne destinataire de la facture"),
    ID_16("16", 0, 38, "Prénom de la personne destinataire de la facture"),
    ID_17("17", 0, 38, "Nom de la personne destinataire de la facture"),
    ID_18("18", 0, -1, "Numéro de la facture"),
    ID_19("19", 0, -1, "Numéro de client"),
    ID_1A("1A", 0, -1, "Numéro du contrat"),
    ID_1B("1B", 0, -1, "Identifiant du souscripteur du contrat"),
    ID_1C("1C", 8, 8, "Date d’effet du contrat"),
    ID_1D("1D", 0, 16, "Montant TTC de la facture"),
    ID_1E("1E", 0, 30, "Numéro de téléphone du bénéficiaire de la prestation"),
    ID_1F("1F", 0, 30, "Numéro de téléphone du destinataire de la facture"),
    ID_1G("1G", 1, 1, "Présence d’un co-bénéficiaire de la prestation non mentionné dans le code"),
    ID_1H("1H", 1, 1, "Présence d’un co-destinataire de la facture non mentionné dans le code"),
    ID_1I("1I", 0, 38, "Ligne 1 de la norme adresse postale du co-bénéficiaire de la prestation"),
    ID_1J("1J", 0, 38, "Qualité et/ou titre du co-bénéficiaire de la prestation"),
    ID_1K("1K", 0, 38, "Prénom du co-bénéficiaire de la prestation"),
    ID_1L("1L", 0, 38, "Nom du co-bénéficiaire de la prestation"),
    ID_1M("1M", 0, 38, "Ligne 1 de la norme adresse postale du co-destinataire de la facture"),
    ID_1N("1N", 0, 38, "Qualité et/ou titre du co-destinataire de la facture"),
    ID_1O("1O", 0, 38, "Prénom du co-destinataire de la facture"),
    ID_1P("1P", 0, 38, "Nom du co-destinataire de la facture"),
    ID_20("20", 0, 38, "Ligne 2 de la norme adresse postale du point de service des prestations"),
    ID_21("21", 0, 38, "Ligne 3 de la norme adresse postale du point de service des prestations"),
    ID_22("22", 0, 38, "Ligne 4 de la norme adresse postale du point de service des prestations"),
    ID_23("23", 0, 38, "Ligne 5 de la norme adresse postale du point de service des prestations"),
    ID_24("24", 5, 5, "Code postal ou code cedex du point de service des prestations"),
    ID_25("25", 0, 32, "Localité de destination ou libellé cedex du point de service des prestations "),
    ID_26("26", 2, 2, "Pays de service des prestations"),
    ID_27("27", 0, 38, "Ligne 2 de la norme adresse postale du destinataire de la facture"),
    ID_28("28", 0, 38, "Ligne 3 de la norme adresse postale du destinataire de la facture"),
    ID_29("29", 0, 38, "Ligne 4 de la norme adresse postale du destinataire de la facture"),
    ID_2A("2A", 0, 38, "Ligne 5 de la norme adresse postale du destinataire de la facture"),
    ID_2B("2B", 5, 5, "Code postal ou code cedex du destinataire de la facture"),
    ID_2C("2C", 0, 32, "Localité de destination ou libellé cedex du destinataire de la facture"),
    ID_2D("2D", 2, 2, "Pays du destinataire de la facture"),
    ID_30("30", 0, 140, "Qualité Nom et Prénom"),
    ID_31("31", 14, 38, "Code IBAN"),
    ID_32("32", 8, 11, "Code BIC/SWIFT"),
    ID_33("33", 0, 30, "Code BBAN"),
    ID_34("34", 2, 2, "Pays de localisation du compte"),
    ID_35("35", 14, 34, "Identifiant SEPAmail (QXBAN)"),
    ID_36("36", 4, 4, "Date de début de période"),
    ID_37("37", 4, 4, "Date de fin de période"),
    ID_38("38", 0, 11, "Solde compte début de période"),
    ID_39("39", 0, 11, "Solde compte fin de période"),
    ID_40("40", 13, 13, "Numéro fiscal"),
    ID_41("41", 0, -1, "Revenu fiscal de référence"),
    ID_42("42", 0, -1, "Situation du foyer"),
    ID_43("43", 0, -1, "Nombre de parts"),
    ID_44("44", 13, 13, "Référence d’avis d’impôt"),
    ID_45("45", 4, 4, "Année des revenus"),
    ID_46("46", 0, 38, "Déclarant 1"),
    ID_47("47", 13, 13, "Numéro fiscal du déclarant 1"),
    ID_48("48", 0, 38, "Déclarant 2"),
    ID_49("49", 13, 13, "Numéro fiscal du déclarant 2"),
    ID_4A("4A", 8, 8, "Date de mise en recouvrement"),
    ID_4B("4B", 8, 8, "Date de la déclaration"),
    ID_4X("4X", 0, -1, "Retenue à la source"),
    ID_4Y("4Y", 0, -1, "Adresse"),
    ID_50("50", 14, 14, "SIRET de l’employeur"),
    ID_51("51", 6, 6, "Nombre d’heures travaillées"),
    ID_52("52", 7, 7, "Cumul du nombre d’heures travaillées"),
    ID_53("53", 4, 4, "Début de période"),
    ID_54("54", 4, 4, "Fin de période"),
    ID_55("55", 8, 8, "Date de début de contrat"),
    ID_56("56", 4, 4, "Date de fin de contrat"),
    ID_57("57", 8, 8, "Date de signature du contrat"),
    ID_58("58", 0, 11, "Salaire net imposable"),
    ID_59("59", 0, 12, "Cumul du salaire net imposable"),
    ID_5A("5A", 0, 11, "Salaire brut du mois"),
    ID_5B("5B", 0, 12, "Cumul du salaire brut"),
    ID_5C("5C", 0, 11, "Salaire net"),
    ID_5D("5D", 0, 38, "Ligne 2 de la norme adresse postale de l’employeur"),
    ID_5E("5E", 0, 38, "Ligne 3 de la norme adresse postale de l’employeur"),
    ID_5F("5F", 0, 38, "Ligne 4 de la norme adresse postale de l’employeur"),
    ID_5G("5G", 0, 38, "Ligne 5 de la norme adresse postale de l’employeur"),
    ID_5H("5H", 5, 5, "Code postal ou code cedex de l’employeur"),
    ID_5I("5I", 0, 32, "Localité de destination ou libellé cedex de l’employeur"),
    ID_5J("5J", 2, 2, "Pays de l’employeur"),
    ID_5K("5K", 0, 50, "Identifiant Cotisant Prestations Sociales"),
    ID_5L("5L", 9, 14, "Numéro de SIRET ou RNA"),
    ID_5M("5M", 0, 38, "Dénomination sociale"),
    ID_5N("5N", 21, 21, "Numéro de dossier d'autorisation de travail"),
    ID_5O("5O", 0, 38, "Nom de l'employeur"),
    ID_5P("5P", 0, 20, "Prénom de l'employeur"),
    ID_60("60", 0, 60, "Liste des prénoms"),
    ID_61("61", 0, 20, "Prénom"),
    ID_62("62", 0, 38, "Nom patronymique"),
    ID_63("63", 0, 38, "Nom d’usage"),
    ID_64("64", 0, 38, "Nom d’épouse/époux"),
    ID_65("65", 2, 2, "Type de pièce d’identité"),
    ID_66("66", 0, 20, "Numéro de la pièce d’identité"),
    ID_67("67", 2, 2, "Nationalité"),
    ID_68("68", 1, 1, "Genre"),
    ID_69("69", 8, 8, "Date de naissance"),
    ID_6A("6A", 0, 32, "Lieu de naissance"),
    ID_6B("6B", 3, 3, "Département du bureau émetteur"),
    ID_6C("6C", 2, 2, "Pays de naissance"),
    ID_6D("6D", 0, 60, "Nom et prénom du père"),
    ID_6E("6E", 0, 60, "Nom et prénom de la mère"),
    ID_6F("6F", 0, 90, "Machine Readable Zone (Zone de Lecture Automatique, ZLA)"),
    ID_6G("6G", 1, 38, "Nom"),
    ID_6H("6H", 1, 10, "Civilité"),
    ID_6I("6I", 2, 2, "Pays émetteur"),
    ID_6J("6J", 1, 1, "Type de document étranger"),
    ID_6K("6K", 19, 19, "Numéro de la demande de document étranger"),
    ID_6L("6L", 8, 8, "Date de dépôt de la demande"),
    ID_6M("6M", 0, 40, "Catégorie du titre"),
    ID_6N("6N", 8, 8, "Date de début de validité"),
    ID_6O("6O", 8, 8, "Date de fin de validité"),
    ID_6P("6P", 0, 40, "Autorisation"),
    ID_6Q("6Q", 0, 10, "Numéro d’étranger"),
    ID_6R("6R", 12, 12, "Numéro de visa"),
    ID_6S("6S", 0, 38, "Ligne 2 de l’adresse postale du domicile"),
    ID_6T("6T", 0, 38, "Ligne 3 de l’adresse postale du domicile"),
    ID_6U("6U", 0, 38, "Ligne 4 de l’adresse postale du domicile"),
    ID_6V("6V", 0, 38, "Ligne 5 de l’adresse postale du domicile"),
    ID_6W("6W", 5, 5, "Code postal ou code cedex de l’adresse postale du domicile"),
    ID_6X("6X", 0, 32, "Commune de l’adresse postale du domicile"),
    ID_6Y("6Y", 2, 2, "Code pays de l’adresse postale du domicile"),
    ID_6Z("6Z", 9, 11, "Numéro d'étranger de l'autorisation de travail"),
    ID_70("70", 12, 12, "Date et heure du décès"),
    ID_71("71", 12, 12, "Date et heure du constat de décès"),
    ID_72("72", 0, 38, "Nom du défunt"),
    ID_73("73", 0, 60, "Prénoms du défunt"),
    ID_74("74", 0, 38, "Nom de jeune fille du défunt"),
    ID_75("75", 8, 8, "Date de naissance du défunt"),
    ID_76("76", 1, 1, "Genre du défunt"),
    ID_77("77", 0, 45, "Commune de décès"),
    ID_78("78", 5, 5, "Code postal de la commune de décès"),
    ID_79("79", 0, 114, "Adresse du domicile du défunt"),
    ID_7A("7A", 5, 5, "Code postal du domicile du défunt"),
    ID_7B("7B", 0, 45, "Commune du domicile du défunt"),
    ID_7C("7C", 1, 1, "Obstacle médico-légal"),
    ID_7D("7D", 1, 1, "Mise en bière"),
    ID_7E("7E", 1, 1, "Obstacle aux soins de conservation"),
    ID_7F("7F", 1, 1, "Obstacle aux dons du corps"),
    ID_7G("7G", 1, 1, "Recherche de la cause du décès"),
    ID_7H("7H", 2, 2, "Délai de transport du corps"),
    ID_7I("7I", 1, 1, "Prothèse avec pile"),
    ID_7J("7J", 1, 1, "Retrait de la pile de prothèse"),
    ID_7K("7K", 13, 13, "Code NNC"),
    ID_7L("7L", 9, 9, "Code Finess de l'organisme agréé"),
    ID_7M("7M", 0, 64, "Identification du médecin"),
    ID_7N("7N", 0, 128, "Lieu de validation du certificat de décès"),
    ID_7O("7O", 1, 1, "Certificat de décès supplémentaire"),
    ID_80("80", 0, 38, "Nom"),
    ID_81("81", 0, 60, "Prénoms"),
    ID_82("82", 0, 20, "Numéro de carte"),
    ID_83("83", 0, 40, "Organisme de tutelle"),
    ID_84("84", 0, 40, "Profession"),
    ID_85("85", 17, 17, "Numéro de permis de chasser"),
    ID_86("86", 12, 12, "Numéro de licence"),
    ID_90("90", 0, 38, "Identité de l'huissier de justice"),
    ID_91("91", 0, 38, "Identité ou raison sociale du demandeur"),
    ID_92("92", 0, 38, "Identité ou raison sociale du destinataire"),
    ID_93("93", 0, 38, "Identité ou raison sociale de tiers concerné"),
    ID_94("94", 0, 38, "Intitulé de l'acte"),
    ID_95("95", 0, 18, "Numéro de l'acte"),
    ID_96("96", 8, 8, "Date de signature de l'acte"),
    ID_A0("A0", 2, 2, "Pays ayant émis l’immatriculation du véhicule"),
    ID_A1("A1", 0, 17, "Immatriculation du véhicule"),
    ID_A2("A2", 0, 17, "Marque du véhicule"),
    ID_A3("A3", 0, 17, "Nom commercial du véhicule"),
    ID_A4("A4", 17, 17, "Numéro de série du véhicule (VIN)"),
    ID_A5("A5", 3, 3, "Catégorie du véhicule"),
    ID_A6("A6", 2, 2, "Carburant"),
    ID_A7("A7", 3, 3, "Taux d’émission de CO2 du véhicule (en g/km)"),
    ID_A8("A8", 0, 12, "Indication de la classe environnementale de réception CE"),
    ID_A9("A9", 3, 3, "Classe d’émission polluante"),
    ID_AA("AA", 8, 8, "Date de première immatriculation du véhicule"),
    ID_AB("AB", 0, 8, "Type de lettre"),
    ID_AC("AC", 0, 19, "N° Dossier"),
    ID_AD("AD", 4, 4, "Date Infraction"),
    ID_AE("AE", 4, 4, "Heure de l’infraction"),
    ID_AF("AF", 1, 1, "Nombre de points retirés lors de l’infraction"),
    ID_AG("AG", 1, 1, "Solde de points"),
    ID_AH("AH", 0, 30, "Numéro de la carte"),
    ID_AI("AI", 8, 8, "Date d’expiration initiale"),
    ID_AJ("AJ", 13, 13, "Numéro EVTC"),
    ID_AK("AK", 7, 7, "Numéro de macaron"),
    ID_AL("AL", 11, 11, "Numéro de la carte"),
    ID_AM("AM", 0, 5, "Motif de sur-classement"),
    ID_AN("AN", 8, 8, "Kilométrage"),
    ID_B0("B0", 0, 60, "Liste des prénoms"),
    ID_B1("B1", 0, 20, "Prénom"),
    ID_B2("B2", 0, 38, "Nom patronymique"),
    ID_B3("B3", 0, 38, "Nom d'usage"),
    ID_B4("B4", 0, 38, "Nom d'épouse/époux"),
    ID_B5("B5", 2, 2, "Nationalité"),
    ID_B6("B6", 1, 1, "Genre"),
    ID_B7("B7", 8, 8, "Date de naissance"),
    ID_B8("B8", 0, 32, "Lieu de naissance"),
    ID_B9("B9", 2, 2, "Pays de naissance"),
    ID_BA("BA", 1, 1, "Mention obtenue"),
    ID_BB("BB", 0, 50, "Numéro ou code d'identification de l'étudiant"),
    ID_BC("BC", 0, 20, "Numéro du diplôme"),
    ID_BD("BD", 1, 1, "Niveau du diplôme selon la classification CEC"),
    ID_BE("BE", 3, 3, "Crédits ECTS obtenus"),
    ID_BF("BF", 3, 3, "Année universitaire"),
    ID_BG("BG", 2, 2, "Type de diplôme"),
    ID_BH("BH", 0, 30, "Domaine"),
    ID_BI("BI", 0, 30, "Mention"),
    ID_BJ("BJ", 0, 30, "Spécialité"),
    ID_BK("BK", 14, 14, "Numéro de l'Attestation de versement de la CVE"),
    ID_C0("C0", 1, 1, "Genre du vendeur"),
    ID_C1("C1", 0, 38, "Nom patronymique du vendeur"),
    ID_C2("C2", 0, 20, "Prénom du vendeur"),
    ID_C3("C3", 12, 12, "Date et heure de la cession"),
    ID_C4("C4", 8, 8, "Date de la signature du vendeur"),
    ID_C5("C5", 1, 1, "Genre de l’acheteur"),
    ID_C6("C6", 0, 38, "Nom patronymique de l’acheteur"),
    ID_C7("C7", 0, 20, "Prénom de l’acheteur"),
    ID_C8("C8", 0, 38, "Ligne 4 de la norme adresse postale du domicile de l’acheteur"),
    ID_C9("C9", 5, 5, "Code postal ou code cedex du domicile de l’acheteur"),
    ID_CA("CA", 0, 45, "Commune du domicile de l’acheteur"),
    ID_CB("CB", 10, 10, "N° d’enregistrement"),
    ID_CC("CC", 12, 12, "Date et heure d'enregistrement dans le SIV"),
    ;

    private final String id;
    private final int minSize;
    private final int maxSize;
    private final String label;

    TwoDDocDataType(String id, int minSize, int maxSize, String label) {
        this.id = id;
        this.minSize = minSize;
        this.maxSize = maxSize;
        this.label = label;
    }

    static TwoDDocDataType of(String id) {
        return TwoDDocDataType.valueOf("ID_" + id);
    }

    boolean hasFixedSize() {
        return minSize == maxSize;
    }

}
