CREATE TABLE IF NOT EXISTS document_denied_reasons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checked_options VARCHAR(255) ARRAY,
    checked_options_id INTEGER ARRAY,
    message_data BOOLEAN NOT NULL DEFAULT TRUE,
    comment VARCHAR(255),
    message_id BIGINT,
    document_id BIGINT,
    creation_date TIMESTAMP,
    document_category VARCHAR(255),
    document_sub_category VARCHAR(255),
    document_category_step VARCHAR(255),
    document_tenant_type VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS storage_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    path VARCHAR(255),
    label VARCHAR(255),
    content_type VARCHAR(255),
    size BIGINT,
    md5 VARCHAR(255),
    status VARCHAR(255),
    provider VARCHAR(255),
    bucket VARCHAR(255),
    providers VARCHAR(255) ARRAY,
    encryption_key_id BIGINT,
    created_date TIMESTAMP,
    last_modified_date TIMESTAMP,
    created_by VARCHAR(255),
    last_modified_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS tenant_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creation_date TIMESTAMP,
    message_id BIGINT,
    operator_id BIGINT,
    tenant_id BIGINT,
    log_details VARCHAR(4000),
    log_type VARCHAR(255),
    user_apis BIGINT ARRAY
);

CREATE TABLE IF NOT EXISTS feature_flag (
    "key" VARCHAR(100) PRIMARY KEY,
    active BOOLEAN NOT NULL,
    only_for_new_user BOOLEAN NOT NULL,
    rollout_pct INT NOT NULL,
    created_at TIMESTAMP,
    deployment_date TIMESTAMP,
    updated_at TIMESTAMP,
    description VARCHAR(4000)
);

CREATE TABLE IF NOT EXISTS feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value" BOOLEAN NOT NULL,
    creation_date TIMESTAMP
);

CREATE TABLE IF NOT EXISTS property_id (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property BIGINT,
    "value" VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "key" VARCHAR(255) NOT NULL UNIQUE,
    "value" VARCHAR(255)
);
