package fr.dossierfacile.scheduler.tasks;

public enum TaskName {

    CHECK_API_ADEME,
    GARBAGE_COLLECTION,
    OWNER_DELETE,
    OWNER_WARNINGS_1,
    OWNER_WARNINGS_2,
    TENANT_WARNINGS,
    TENANT_ARCHIVING,
    TENANT_DELETION,
    STORAGE_FILES_BACKUP,
    STORAGE_FILES_BACKUP_RETRY,
    STORAGE_FILES_DELETION,
    STORAGE_FILES_DELETION_RETRY,
    PDF_GENERATION,
    DELETE_FAILED_DOCUMENT;

}
