package fr.dossierfacile.scheduler.tasks;

public enum TaskName {

    GARBAGE_COLLECTION,
    TENANT_WARNINGS,
    TENANT_ARCHIVING,
    TENANT_DELETION,
    STORAGE_FILES_BACKUP,
    STORAGE_FILES_BACKUP_RETRY,
    STORAGE_FILES_DELETION,
    STORAGE_FILES_DELETION_RETRY,
    PDF_GENERATION,
    DELETE_FAILED_DOCUMENT;

}
