--
-- PostgreSQL database dump
--

-- Dumped from database version 12.22 (Debian 12.22-1.pgdg120+1)
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


--
-- Name: refresh_mv(text); Type: PROCEDURE; Schema: public; Owner: -
--

CREATE PROCEDURE public.refresh_mv(view_name text)
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$
                BEGIN
                    EXECUTE 'REFRESH MATERIALIZED VIEW ' || quote_ident(view_name);
                END;
                $$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: apartment_sharing; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.apartment_sharing (
    id bigint NOT NULL,
    token character varying(255) DEFAULT NULL::character varying,
    token_public character varying(255) DEFAULT NULL::character varying,
    operator_date timestamp without time zone,
    application_type character varying,
    dossier_pdf_document_status character varying(20),
    last_update_date timestamp without time zone,
    pdf_dossier_file_id bigint
);


--
-- Name: apartment_sharing_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.apartment_sharing_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: apartment_sharing_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.apartment_sharing_id_seq OWNED BY public.apartment_sharing.id;


--
-- Name: apartment_sharing_link; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.apartment_sharing_link (
    id bigint NOT NULL,
    creation_date timestamp without time zone,
    apartment_sharing_id bigint NOT NULL,
    token uuid,
    full_data boolean NOT NULL,
    disabled boolean NOT NULL,
    link_type character varying(255) NOT NULL,
    email character varying(255),
    last_sent_datetime timestamp without time zone,
    title character varying(255) DEFAULT NULL::character varying,
    expiration_date timestamp without time zone,
    deleted boolean DEFAULT false NOT NULL,
    created_by bigint,
    partner_id bigint,
    property_id bigint,
    failed_attempt_count integer DEFAULT 0 NOT NULL,
    first_failed_attempt_at timestamp without time zone
);


--
-- Name: apartment_sharing_link_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.apartment_sharing_link_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: apartment_sharing_link_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.apartment_sharing_link_id_seq OWNED BY public.apartment_sharing_link.id;


--
-- Name: bo_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bo_user (
    id bigint NOT NULL
);


--
-- Name: bo_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bo_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bo_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: callback_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.callback_log (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    partner_id bigint NOT NULL,
    tenant_status character varying NOT NULL,
    creation_date timestamp without time zone NOT NULL,
    content_json text
);


--
-- Name: callback_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.callback_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: callback_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.callback_log_id_seq OWNED BY public.callback_log.id;


--
-- Name: confirmation_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.confirmation_token (
    id bigint NOT NULL,
    creation_date timestamp without time zone,
    token character varying(255),
    user_id bigint NOT NULL
);


--
-- Name: confirmation_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.confirmation_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: confirmation_token_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.confirmation_token_id_seq OWNED BY public.confirmation_token.id;


--
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


--
-- Name: document; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document (
    id bigint NOT NULL,
    document_category character varying NOT NULL,
    tenant_id bigint,
    custom_text character varying,
    monthly_sum integer,
    guarantor_id bigint,
    document_sub_category character varying,
    document_status character varying DEFAULT 'NO_PROCESSED'::character varying NOT NULL,
    name character varying,
    no_document boolean,
    creation_date timestamp without time zone,
    document_denied_reasons_id bigint,
    avis_detected boolean,
    watermark_file_id bigint,
    last_modified_date timestamp without time zone,
    document_category_step character varying(50)
);


--
-- Name: document_analysis_report; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_analysis_report (
    id bigint NOT NULL,
    document_id bigint,
    analysis_status character varying(255) NOT NULL,
    failed_rules jsonb,
    comment text,
    passed_rules jsonb,
    inconclusive_rules jsonb,
    created_at timestamp without time zone DEFAULT '1970-01-01 00:00:00'::timestamp without time zone,
    data_document_id bigint
);


--
-- Name: document_analysis_report_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.document_analysis_report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_analysis_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: document_denied_options; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_denied_options (
    id integer NOT NULL,
    message_value text,
    document_sub_category character varying,
    document_user_type character varying,
    code character varying(255),
    document_category character varying(50) DEFAULT NULL::character varying
);


--
-- Name: document_denied_options_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.document_denied_options_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: document_denied_options_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.document_denied_options_id_seq OWNED BY public.document_denied_options.id;


--
-- Name: document_denied_reasons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_denied_reasons (
    id bigint NOT NULL,
    checked_options character varying[],
    comment character varying,
    message_id bigint,
    checked_options_id integer[],
    message_data boolean DEFAULT false NOT NULL,
    document_id bigint,
    creation_date timestamp without time zone,
    document_category character varying(50) DEFAULT NULL::character varying,
    document_sub_category character varying(50),
    document_category_step character varying(50),
    document_tenant_type character varying(50)
);


--
-- Name: document_denied_reasons_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.document_denied_reasons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: document_denied_reasons_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.document_denied_reasons_id_seq OWNED BY public.document_denied_reasons.id;


--
-- Name: document_ia_file_analysis; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_ia_file_analysis (
    id bigint NOT NULL,
    document_ia_workflow_id character varying(255) NOT NULL,
    document_ia_execution_id character varying(255),
    file_id bigint NOT NULL,
    analysis_status character varying(32) NOT NULL,
    result text,
    creation_date timestamp without time zone DEFAULT now() NOT NULL,
    last_modified_date timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: document_ia_file_analysis_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.document_ia_file_analysis ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_ia_file_analysis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: document_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.document_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: document_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.document_id_seq OWNED BY public.document.id;


--
-- Name: encryption_key; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.encryption_key (
    id bigint NOT NULL,
    status character varying(32),
    algorithm character varying(32),
    format character varying(32),
    encoded bytea,
    version integer DEFAULT 0 NOT NULL
);


--
-- Name: encryption_key_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.encryption_key ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.encryption_key_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feature_flag; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feature_flag (
    key character varying(100) NOT NULL,
    description text,
    active boolean DEFAULT false NOT NULL,
    only_for_new_user boolean DEFAULT true NOT NULL,
    rollout_pct integer DEFAULT 0 NOT NULL,
    deployment_date timestamp without time zone DEFAULT now() NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: feedback; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feedback (
    id bigint NOT NULL,
    value boolean NOT NULL,
    creation_date timestamp without time zone NOT NULL
);


--
-- Name: feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.feedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: file; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.file (
    id bigint NOT NULL,
    document_id bigint NOT NULL,
    creation_date timestamp without time zone,
    number_of_pages integer DEFAULT 0 NOT NULL,
    preview_file_id bigint,
    storage_file_id bigint
);


--
-- Name: file_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: file_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.file_id_seq OWNED BY public.file.id;


--
-- Name: file_metadata; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.file_metadata (
    id bigint NOT NULL,
    file_id bigint,
    metadata text
);


--
-- Name: file_metadata_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.file_metadata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.file_metadata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: garbage_collection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.garbage_collection (
    provider character varying(128) NOT NULL,
    current_marker character varying(128),
    deleted_objects bigint DEFAULT 0 NOT NULL
);


--
-- Name: garbage_sequence; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.garbage_sequence (
    name character varying(32) NOT NULL,
    value bigint,
    last_update_date timestamp without time zone
);


--
-- Name: guarantor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guarantor (
    id bigint NOT NULL,
    first_name character varying(255) DEFAULT NULL::character varying,
    last_name character varying(255) DEFAULT NULL::character varying,
    tenant_id bigint,
    type_guarantor character varying DEFAULT 'NATURAL_PERSON'::character varying NOT NULL,
    legal_person_name character varying
);


--
-- Name: guarantor_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.guarantor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: guarantor_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.guarantor_id_seq OWNED BY public.guarantor.id;


--
-- Name: operator_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.operator_log (
    id bigint NOT NULL,
    tenant_id bigint,
    operator_id bigint,
    tenant_status character varying,
    action_type character varying NOT NULL,
    creation_date timestamp without time zone NOT NULL,
    processed_documents integer,
    time_spent integer,
    metadata jsonb
);


--
-- Name: latest_operator; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.latest_operator AS
 SELECT ol.tenant_id,
    ol.operator_id
   FROM (public.operator_log ol
     JOIN ( SELECT operator_log.tenant_id,
            max(operator_log.creation_date) AS creation_date
           FROM public.operator_log
          GROUP BY operator_log.tenant_id) latest ON (((ol.tenant_id = latest.tenant_id) AND (ol.creation_date = latest.creation_date))))
  WITH NO DATA;


--
-- Name: link_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.link_log (
    id bigint NOT NULL,
    apartment_sharing_id bigint NOT NULL,
    token uuid NOT NULL,
    link_type character varying NOT NULL,
    creation_date timestamp without time zone NOT NULL,
    ip_address character varying
);


--
-- Name: link_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.link_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: link_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.link_log_id_seq OWNED BY public.link_log.id;


--
-- Name: message; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.message (
    id bigint NOT NULL,
    creation_date timestamp without time zone,
    message_body text,
    message_status character varying,
    from_user bigint,
    to_user bigint,
    custom_message boolean DEFAULT false
);


--
-- Name: message_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: message_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.message_id_seq OWNED BY public.message.id;


--
-- Name: operator_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.operator_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: operator_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.operator_log_id_seq OWNED BY public.operator_log.id;


--
-- Name: owner; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.owner (
    id bigint NOT NULL,
    slug character varying(255),
    step_register_owner integer,
    example boolean DEFAULT false,
    warnings integer DEFAULT 0 NOT NULL
);


--
-- Name: owner_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.owner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: owner_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.owner_id_seq OWNED BY public.owner.id;


--
-- Name: owner_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.owner_log (
    id bigint NOT NULL,
    owner_id bigint NOT NULL,
    creation_date timestamp without time zone NOT NULL,
    log_type character varying(128) NOT NULL,
    json_profile jsonb
);


--
-- Name: owner_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.owner_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.owner_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_recovery_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_recovery_token (
    id bigint NOT NULL,
    expiration_date timestamp without time zone,
    token character varying(80) NOT NULL,
    user_id bigint
);


--
-- Name: password_recovery_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.password_recovery_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: password_recovery_token_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.password_recovery_token_id_seq OWNED BY public.password_recovery_token.id;


--
-- Name: processing_capacity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.processing_capacity (
    id bigint NOT NULL,
    date date NOT NULL,
    daily_count integer NOT NULL
);


--
-- Name: processing_capacity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.processing_capacity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.processing_capacity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: property; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.property (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    token character varying(255) DEFAULT NULL::character varying,
    owner_id bigint,
    creation_date timestamp without time zone,
    count_visit integer,
    property_id character varying(255),
    rent_cost double precision DEFAULT 0,
    displayed boolean DEFAULT true NOT NULL,
    notification boolean DEFAULT true NOT NULL,
    cant_email_sent_prospect integer DEFAULT 0,
    validated boolean DEFAULT false NOT NULL,
    type character varying,
    furniture character varying,
    address character varying,
    charges_cost double precision DEFAULT 0,
    living_space double precision DEFAULT 0,
    energy_consumption integer,
    co2emission integer,
    validated_date timestamp without time zone,
    ademe_number text,
    ademe_api_result jsonb,
    dpe_date timestamp without time zone,
    dpe_not_required boolean DEFAULT false
);


--
-- Name: property_apartment_sharing; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.property_apartment_sharing (
    id bigint NOT NULL,
    access_full boolean NOT NULL,
    apartment_sharing_id bigint,
    property_id bigint,
    token character varying(255) DEFAULT NULL::character varying
);


--
-- Name: property_apartment_sharing_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.property_apartment_sharing_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: property_apartment_sharing_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.property_apartment_sharing_id_seq OWNED BY public.property_apartment_sharing.id;


--
-- Name: property_id; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.property_id (
    id bigint NOT NULL,
    value character varying(255),
    property bigint
);


--
-- Name: property_id_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.property_id_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: property_id_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.property_id_id_seq OWNED BY public.property_id.id;


--
-- Name: property_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.property_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: property_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.property_id_seq OWNED BY public.property.id;


--
-- Name: property_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.property_log (
    id bigint NOT NULL,
    property_id bigint NOT NULL,
    creation_date timestamp without time zone NOT NULL,
    log_type character varying(128) NOT NULL,
    apartment_sharing_id bigint
);


--
-- Name: property_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.property_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: property_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.property_log_id_seq OWNED BY public.property_log.id;


--
-- Name: queue_message; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.queue_message (
    id bigint NOT NULL,
    "timestamp" bigint NOT NULL,
    document_id bigint,
    status character varying(64) NOT NULL,
    queue_name character varying(128),
    file_id bigint
);


--
-- Name: queue_message_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.queue_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.queue_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenant; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tenant (
    id bigint NOT NULL,
    tenant_type character varying(255) DEFAULT NULL::character varying,
    apartment_sharing_id bigint,
    satisfaction_survey integer,
    accept_access boolean,
    zip_code character varying,
    honor_declaration boolean DEFAULT false NOT NULL,
    last_update_date timestamp without time zone,
    clarification character varying(2000) DEFAULT NULL::character varying,
    status character varying,
    operator_date_time timestamp without time zone,
    warnings integer DEFAULT 0 NOT NULL,
    operator_comment text,
    abroad boolean DEFAULT false,
    tenant_first_name character varying(255),
    tenant_last_name character varying(255),
    tenant_preferred_name character varying(255),
    owner_type character varying(50)
);


--
-- Name: ranked_tenant; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.ranked_tenant AS
 SELECT t.id AS tid,
    t.last_update_date,
    lo.operator_id,
    row_number() OVER (ORDER BY t.last_update_date) AS rank
   FROM (public.tenant t
     LEFT JOIN public.latest_operator lo ON ((t.id = lo.tenant_id)))
  WHERE (((t.status)::text = 'TO_PROCESS'::text) AND (t.honor_declaration = true) AND (NOT (EXISTS ( SELECT 1
           FROM public.document d
          WHERE ((d.tenant_id = t.id) AND (d.watermark_file_id IS NULL))))) AND (NOT (EXISTS ( SELECT 1
           FROM (public.guarantor g
             JOIN public.document d2 ON ((g.id = d2.guarantor_id)))
          WHERE ((g.tenant_id = t.id) AND (d2.watermark_file_id IS NULL))))))
  WITH NO DATA;


--
-- Name: stats; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stats (
    id bigint NOT NULL,
    key character varying(255) NOT NULL,
    value character varying(255)
);


--
-- Name: stats_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: storage_file; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.storage_file (
    id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp without time zone,
    last_modified_by character varying(255),
    last_modified_date timestamp without time zone,
    name character varying(255),
    path character varying(255),
    label character varying(255),
    content_type character varying(255),
    size bigint,
    md5 character varying(255),
    provider character varying(255),
    encryption_key_id bigint,
    providers character varying[],
    status character varying(16),
    bucket character varying(50) DEFAULT 'NONE'::character varying
);


--
-- Name: storage_file_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.storage_file ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.storage_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenant_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tenant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: tenant_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tenant_id_seq OWNED BY public.tenant.id;


--
-- Name: tenant_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tenant_log (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    operator_id bigint,
    log_type character varying NOT NULL,
    creation_date timestamp without time zone NOT NULL,
    message_id bigint,
    user_apis bigint[],
    json_profile jsonb,
    log_details jsonb
);


--
-- Name: tenant_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tenant_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: tenant_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tenant_log_id_seq OWNED BY public.tenant_log.id;


--
-- Name: tenant_userapi; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tenant_userapi (
    tenant_id bigint NOT NULL,
    userapi_id bigint NOT NULL,
    access_granted_date timestamp without time zone
);


--
-- Name: user_account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_account (
    id bigint NOT NULL,
    creation_date timestamp without time zone,
    email character varying(255) DEFAULT NULL::character varying,
    first_name character varying(255) DEFAULT NULL::character varying,
    last_name character varying(255) DEFAULT NULL::character varying,
    last_login_date timestamp without time zone,
    update_date_time timestamp without time zone,
    image_url character varying(255),
    provider character varying(20) DEFAULT 'local'::character varying,
    provider_id character varying(255),
    enabled boolean DEFAULT true,
    keycloak_id character varying,
    france_connect boolean DEFAULT false NOT NULL,
    france_connect_sub character varying,
    france_connect_birth_date character varying,
    france_connect_birth_place character varying,
    france_connect_birth_country character varying,
    preferred_name character varying,
    user_type character varying,
    acquisition_campaign character varying(128),
    acquisition_source character varying(128),
    acquisition_medium character varying(128)
);


--
-- Name: user_account_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_account_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_account_id_seq OWNED BY public.user_account.id;


--
-- Name: user_api; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_api (
    id bigint NOT NULL,
    url_callback character varying(255) DEFAULT NULL::character varying,
    name character varying(255) DEFAULT NULL::character varying,
    name2 character varying(255),
    site character varying(255),
    partner_api_key_callback character varying(255),
    disabled boolean,
    logo_url character varying(255),
    email character varying(255)
);


--
-- Name: user_api_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_api_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_api_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_api_id_seq OWNED BY public.user_api.id;


--
-- Name: user_feature_assignment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_feature_assignment (
    user_id bigint NOT NULL,
    feature_key character varying(100) NOT NULL,
    enabled boolean DEFAULT false NOT NULL,
    bucket integer NOT NULL,
    rollout_pct integer NOT NULL,
    assigned_at timestamp without time zone DEFAULT now() NOT NULL,
    assignment_source character varying(20) NOT NULL
);


--
-- Name: user_feature_assignment_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_feature_assignment_history (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    feature_key character varying(100) NOT NULL,
    enabled boolean NOT NULL,
    bucket integer NOT NULL,
    rollout_pct integer NOT NULL,
    changed_at timestamp without time zone DEFAULT now() NOT NULL,
    reason character varying(50) NOT NULL
);


--
-- Name: user_feature_assignment_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_feature_assignment_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_feature_assignment_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_roles (
    id bigint NOT NULL,
    role integer,
    user_id bigint
);


--
-- Name: user_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_roles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_roles_id_seq OWNED BY public.user_roles.id;


--
-- Name: watermark_document; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.watermark_document (
    id bigint NOT NULL,
    created_date timestamp without time zone,
    token character varying(255),
    pdf_status character varying(64),
    pdf_file_id bigint,
    text character varying(255)
);


--
-- Name: watermark_document_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.watermark_document ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.watermark_document_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: watermark_document_storage_file; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.watermark_document_storage_file (
    watermark_document_id bigint,
    storage_file_id bigint
);


--
-- Name: apartment_sharing id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.apartment_sharing ALTER COLUMN id SET DEFAULT nextval('public.apartment_sharing_id_seq'::regclass);


--
-- Name: apartment_sharing_link id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.apartment_sharing_link ALTER COLUMN id SET DEFAULT nextval('public.apartment_sharing_link_id_seq'::regclass);


--
-- Name: callback_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.callback_log ALTER COLUMN id SET DEFAULT nextval('public.callback_log_id_seq'::regclass);


--
-- Name: confirmation_token id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.confirmation_token ALTER COLUMN id SET DEFAULT nextval('public.confirmation_token_id_seq'::regclass);


--
-- Name: document id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document ALTER COLUMN id SET DEFAULT nextval('public.document_id_seq'::regclass);


--
-- Name: document_denied_options id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_denied_options ALTER COLUMN id SET DEFAULT nextval('public.document_denied_options_id_seq'::regclass);


--
-- Name: document_denied_reasons id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_denied_reasons ALTER COLUMN id SET DEFAULT nextval('public.document_denied_reasons_id_seq'::regclass);


--
-- Name: file id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file ALTER COLUMN id SET DEFAULT nextval('public.file_id_seq'::regclass);


--
-- Name: guarantor id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guarantor ALTER COLUMN id SET DEFAULT nextval('public.guarantor_id_seq'::regclass);


--
-- Name: link_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.link_log ALTER COLUMN id SET DEFAULT nextval('public.link_log_id_seq'::regclass);


--
-- Name: message id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message ALTER COLUMN id SET DEFAULT nextval('public.message_id_seq'::regclass);


--
-- Name: operator_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operator_log ALTER COLUMN id SET DEFAULT nextval('public.operator_log_id_seq'::regclass);


--
-- Name: owner id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.owner ALTER COLUMN id SET DEFAULT nextval('public.owner_id_seq'::regclass);


--
-- Name: password_recovery_token id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_recovery_token ALTER COLUMN id SET DEFAULT nextval('public.password_recovery_token_id_seq'::regclass);


--
-- Name: property id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property ALTER COLUMN id SET DEFAULT nextval('public.property_id_seq'::regclass);


--
-- Name: property_apartment_sharing id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_apartment_sharing ALTER COLUMN id SET DEFAULT nextval('public.property_apartment_sharing_id_seq'::regclass);


--
-- Name: property_id id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_id ALTER COLUMN id SET DEFAULT nextval('public.property_id_id_seq'::regclass);


--
-- Name: property_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_log ALTER COLUMN id SET DEFAULT nextval('public.property_log_id_seq'::regclass);


--
-- Name: tenant id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant ALTER COLUMN id SET DEFAULT nextval('public.tenant_id_seq'::regclass);


--
-- Name: tenant_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant_log ALTER COLUMN id SET DEFAULT nextval('public.tenant_log_id_seq'::regclass);


--
-- Name: user_account id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_account ALTER COLUMN id SET DEFAULT nextval('public.user_account_id_seq'::regclass);


--
-- Name: user_api id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_api ALTER COLUMN id SET DEFAULT nextval('public.user_api_id_seq'::regclass);


--
-- Name: user_roles id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles ALTER COLUMN id SET DEFAULT nextval('public.user_roles_id_seq'::regclass);


--
-- Name: apartment_sharing apartment_sharing_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.apartment_sharing
    ADD CONSTRAINT apartment_sharing_pkey PRIMARY KEY (id);


--
-- Name: bo_user bo_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bo_user
    ADD CONSTRAINT bo_user_pkey PRIMARY KEY (id);


--
-- Name: callback_log callback_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.callback_log
    ADD CONSTRAINT callback_log_pkey PRIMARY KEY (id);


--
-- Name: confirmation_token confirmation_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.confirmation_token
    ADD CONSTRAINT confirmation_token_pkey PRIMARY KEY (id);


--
-- Name: document_analysis_report document_analysis_report_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_analysis_report
    ADD CONSTRAINT document_analysis_report_pkey PRIMARY KEY (id);


--
-- Name: document_denied_reasons document_denied_reasons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_denied_reasons
    ADD CONSTRAINT document_denied_reasons_pkey PRIMARY KEY (id);


--
-- Name: document document_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document
    ADD CONSTRAINT document_pk PRIMARY KEY (id);


--
-- Name: user_account email_type_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_account
    ADD CONSTRAINT email_type_uniq UNIQUE (email, user_type);


--
-- Name: feature_flag feature_flag_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feature_flag
    ADD CONSTRAINT feature_flag_pkey PRIMARY KEY (key);


--
-- Name: file_metadata file_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file_metadata
    ADD CONSTRAINT file_metadata_pkey PRIMARY KEY (id);


--
-- Name: file file_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file
    ADD CONSTRAINT file_pk PRIMARY KEY (id);


--
-- Name: garbage_collection garbage_collection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.garbage_collection
    ADD CONSTRAINT garbage_collection_pkey PRIMARY KEY (provider);


--
-- Name: garbage_sequence garbage_sequence_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.garbage_sequence
    ADD CONSTRAINT garbage_sequence_pkey PRIMARY KEY (name);


--
-- Name: guarantor guarantor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guarantor
    ADD CONSTRAINT guarantor_pkey PRIMARY KEY (id);


--
-- Name: document_denied_options id_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_denied_options
    ADD CONSTRAINT id_pk PRIMARY KEY (id);


--
-- Name: link_log link_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.link_log
    ADD CONSTRAINT link_log_pkey PRIMARY KEY (id);


--
-- Name: message message_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT message_pkey PRIMARY KEY (id);


--
-- Name: operator_log operator_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operator_log
    ADD CONSTRAINT operator_log_pkey PRIMARY KEY (id);


--
-- Name: owner_log owner_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.owner_log
    ADD CONSTRAINT owner_log_pkey PRIMARY KEY (id);


--
-- Name: owner owner_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.owner
    ADD CONSTRAINT owner_pkey PRIMARY KEY (id);


--
-- Name: password_recovery_token password_recovery_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_recovery_token
    ADD CONSTRAINT password_recovery_token_pkey PRIMARY KEY (id);


--
-- Name: document_ia_file_analysis pk_document_ia_file_analysis; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_ia_file_analysis
    ADD CONSTRAINT pk_document_ia_file_analysis PRIMARY KEY (id);


--
-- Name: encryption_key pk_encryptionkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.encryption_key
    ADD CONSTRAINT pk_encryptionkey PRIMARY KEY (id);


--
-- Name: feedback pk_feedback; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT pk_feedback PRIMARY KEY (id);


--
-- Name: queue_message pk_queue_message; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.queue_message
    ADD CONSTRAINT pk_queue_message PRIMARY KEY (id);


--
-- Name: stats pk_stats; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stats
    ADD CONSTRAINT pk_stats PRIMARY KEY (id);


--
-- Name: storage_file pk_storagefile; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.storage_file
    ADD CONSTRAINT pk_storagefile PRIMARY KEY (id);


--
-- Name: user_feature_assignment pk_user_feature_assignment; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_feature_assignment
    ADD CONSTRAINT pk_user_feature_assignment PRIMARY KEY (user_id, feature_key);


--
-- Name: watermark_document pk_watermark_document; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.watermark_document
    ADD CONSTRAINT pk_watermark_document PRIMARY KEY (id);


--
-- Name: processing_capacity processing_capacity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.processing_capacity
    ADD CONSTRAINT processing_capacity_pkey PRIMARY KEY (id);


--
-- Name: property_apartment_sharing property_apartment_sharing_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_apartment_sharing
    ADD CONSTRAINT property_apartment_sharing_pkey PRIMARY KEY (id);


--
-- Name: property_id property_id_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_id
    ADD CONSTRAINT property_id_pkey PRIMARY KEY (id);


--
-- Name: property_log property_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_log
    ADD CONSTRAINT property_log_pkey PRIMARY KEY (id);


--
-- Name: property property_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property
    ADD CONSTRAINT property_pkey PRIMARY KEY (id);


--
-- Name: tenant_log tenant_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant_log
    ADD CONSTRAINT tenant_log_pkey PRIMARY KEY (id);


--
-- Name: tenant tenant_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant
    ADD CONSTRAINT tenant_pkey PRIMARY KEY (id);


--
-- Name: tenant_userapi tenant_userapi_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant_userapi
    ADD CONSTRAINT tenant_userapi_pkey PRIMARY KEY (tenant_id, userapi_id);


--
-- Name: document_analysis_report uc_document_analysis_report_document_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_analysis_report
    ADD CONSTRAINT uc_document_analysis_report_document_id UNIQUE (document_id);


--
-- Name: document_denied_options uc_document_denied_options_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_denied_options
    ADD CONSTRAINT uc_document_denied_options_code UNIQUE (code);


--
-- Name: user_account uc_keycloak_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_account
    ADD CONSTRAINT uc_keycloak_id UNIQUE (keycloak_id);


--
-- Name: stats uc_stats_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stats
    ADD CONSTRAINT uc_stats_key UNIQUE (key);


--
-- Name: watermark_document_storage_file uk_cf95r7cpxqdk5b2t7ecx3t7rf; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.watermark_document_storage_file
    ADD CONSTRAINT uk_cf95r7cpxqdk5b2t7ecx3t7rf UNIQUE (storage_file_id);


--
-- Name: user_api user_api_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_api
    ADD CONSTRAINT user_api_pkey PRIMARY KEY (id);


--
-- Name: user_feature_assignment_history user_feature_assignment_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_feature_assignment_history
    ADD CONSTRAINT user_feature_assignment_history_pkey PRIMARY KEY (id);


--
-- Name: user_account user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_account
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);


--
-- Name: apartment_sharing_link_apart_sh_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX apartment_sharing_link_apart_sh_id_index ON public.apartment_sharing_link USING btree (apartment_sharing_id);


--
-- Name: apartment_sharing_link_token_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX apartment_sharing_link_token_index ON public.apartment_sharing_link USING btree (token);


--
-- Name: confirmation_token_user_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX confirmation_token_user_id_index ON public.confirmation_token USING btree (user_id);


--
-- Name: document_denied_reasons_document_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_denied_reasons_document_id_index ON public.document_denied_reasons USING btree (document_id);


--
-- Name: document_guarantor_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_guarantor_id_index ON public.document USING btree (guarantor_id);


--
-- Name: document_name_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_name_index ON public.document USING btree (name);


--
-- Name: document_tenant_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_tenant_id_index ON public.document USING btree (tenant_id);


--
-- Name: file_document_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX file_document_id_index ON public.file USING btree (document_id);


--
-- Name: guarantor_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX guarantor_tenant_id ON public.guarantor USING btree (tenant_id);


--
-- Name: idx_document_ia_file_analysis_file_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_ia_file_analysis_file_id ON public.document_ia_file_analysis USING btree (file_id);


--
-- Name: idx_file_metadata_file_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_file_metadata_file_id ON public.file_metadata USING btree (file_id);


--
-- Name: idx_operator_log_operator_id_action_type_creation_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_operator_log_operator_id_action_type_creation_date ON public.operator_log USING btree (operator_id, action_type, creation_date);


--
-- Name: link_log_token_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX link_log_token_index ON public.link_log USING btree (token);


--
-- Name: message_from_user_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX message_from_user_index ON public.message USING btree (from_user);


--
-- Name: message_to_user_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX message_to_user_index ON public.message USING btree (to_user);


--
-- Name: operator_log_action_type_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX operator_log_action_type_index ON public.operator_log USING btree (action_type);


--
-- Name: operator_log_creation_date_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX operator_log_creation_date_index ON public.operator_log USING btree (creation_date);


--
-- Name: operator_log_operator_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX operator_log_operator_id_index ON public.operator_log USING btree (operator_id);


--
-- Name: owner_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX owner_id_index ON public.property USING btree (owner_id);


--
-- Name: owner_log_owner_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX owner_log_owner_id_index ON public.owner_log USING btree (owner_id);


--
-- Name: pdf_dossier_file_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pdf_dossier_file_id_index ON public.apartment_sharing USING btree (pdf_dossier_file_id);


--
-- Name: preview_file_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX preview_file_id_index ON public.file USING btree (preview_file_id);


--
-- Name: processing_capacity_date_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX processing_capacity_date_index ON public.processing_capacity USING btree (date);


--
-- Name: property_apartment_sharing_property_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX property_apartment_sharing_property_id_index ON public.property_apartment_sharing USING btree (property_id);


--
-- Name: queue_message_queue_name_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX queue_message_queue_name_index ON public.queue_message USING btree (queue_name);


--
-- Name: queue_message_status_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX queue_message_status_index ON public.queue_message USING btree (status);


--
-- Name: storage_file_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX storage_file_id_index ON public.file USING btree (storage_file_id);


--
-- Name: storage_file_path; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX storage_file_path ON public.storage_file USING btree (path);


--
-- Name: storage_file_providers_length_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX storage_file_providers_length_index ON public.storage_file USING btree (array_length(providers, 1));


--
-- Name: storage_file_status_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX storage_file_status_index ON public.storage_file USING btree (status);


--
-- Name: tenant_apartment_sharing_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tenant_apartment_sharing_id_index ON public.tenant USING btree (apartment_sharing_id);


--
-- Name: tenant_honor_declaration; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tenant_honor_declaration ON public.tenant USING btree (honor_declaration);


--
-- Name: tenant_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tenant_id_index ON public.tenant_log USING btree (tenant_id);


--
-- Name: tenant_last_operator_date_time_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tenant_last_operator_date_time_index ON public.tenant USING btree (operator_date_time);


--
-- Name: tenant_last_update_date_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tenant_last_update_date_index ON public.tenant USING btree (last_update_date);


--
-- Name: tenant_log_creation_date_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tenant_log_creation_date_index ON public.tenant_log USING btree (creation_date);


--
-- Name: tenant_log_log_type_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tenant_log_log_type_index ON public.tenant_log USING btree (log_type);


--
-- Name: tenant_log_user_apis_gin_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tenant_log_user_apis_gin_index ON public.tenant_log USING gin (user_apis);


--
-- Name: tenant_operator_date_time_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tenant_operator_date_time_index ON public.tenant USING btree (operator_date_time);


--
-- Name: tenant_status_honor_last_upd_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tenant_status_honor_last_upd_index ON public.tenant USING btree (status, honor_declaration, last_update_date);


--
-- Name: tenant_status_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tenant_status_index ON public.tenant USING btree (status);


--
-- Name: tenant_userapi_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tenant_userapi_index ON public.tenant_userapi USING btree (tenant_id, userapi_id);


--
-- Name: tenant_userapi_tenant_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tenant_userapi_tenant_id_index ON public.tenant_userapi USING btree (tenant_id);


--
-- Name: user_account_keycloak_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_account_keycloak_id_index ON public.user_account USING btree (keycloak_id);


--
-- Name: watermark_document_pdf_file; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX watermark_document_pdf_file ON public.watermark_document USING btree (pdf_file_id);


--
-- Name: watermark_document_storage_file_storage; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX watermark_document_storage_file_storage ON public.watermark_document_storage_file USING btree (storage_file_id);


--
-- Name: watermark_document_storage_file_watermark_document_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX watermark_document_storage_file_watermark_document_id ON public.watermark_document_storage_file USING btree (watermark_document_id);


--
-- Name: watermark_document_token; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX watermark_document_token ON public.watermark_document USING btree (token);


--
-- Name: watermark_file_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX watermark_file_id_index ON public.document USING btree (watermark_file_id);


--
-- Name: apartment_sharing_link apartment_sharing_link_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.apartment_sharing_link
    ADD CONSTRAINT apartment_sharing_link_fkey FOREIGN KEY (apartment_sharing_id) REFERENCES public.apartment_sharing(id) ON DELETE CASCADE;


--
-- Name: document_denied_reasons document_denied_reasons_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_denied_reasons
    ADD CONSTRAINT document_denied_reasons_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.message(id) ON DELETE CASCADE;


--
-- Name: document document_document_denied_reasons_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document
    ADD CONSTRAINT document_document_denied_reasons_id_fkey FOREIGN KEY (document_denied_reasons_id) REFERENCES public.document_denied_reasons(id) ON DELETE SET NULL;


--
-- Name: document document_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document
    ADD CONSTRAINT document_fk FOREIGN KEY (tenant_id) REFERENCES public.tenant(id);


--
-- Name: document document_fk1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document
    ADD CONSTRAINT document_fk1 FOREIGN KEY (guarantor_id) REFERENCES public.guarantor(id) ON DELETE CASCADE;


--
-- Name: file file_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file
    ADD CONSTRAINT file_fk FOREIGN KEY (document_id) REFERENCES public.document(id) ON DELETE CASCADE;


--
-- Name: property_id fk1pats6phuuq9nyt028bfap4ni; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_id
    ADD CONSTRAINT fk1pats6phuuq9nyt028bfap4ni FOREIGN KEY (property) REFERENCES public.property(id);


--
-- Name: confirmation_token fk4nuejr8ptkd46ejwc1uqfceu4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.confirmation_token
    ADD CONSTRAINT fk4nuejr8ptkd46ejwc1uqfceu4 FOREIGN KEY (user_id) REFERENCES public.user_account(id);


--
-- Name: message fk5ihkjs9i5ue1m6ffsyua6tpk1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT fk5ihkjs9i5ue1m6ffsyua6tpk1 FOREIGN KEY (to_user) REFERENCES public.user_account(id);


--
-- Name: property_apartment_sharing fk69euji10vyg39g3f4cvlx5l24; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_apartment_sharing
    ADD CONSTRAINT fk69euji10vyg39g3f4cvlx5l24 FOREIGN KEY (property_id) REFERENCES public.property(id);


--
-- Name: user_feature_assignment fk_assignment_feature_flag; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_feature_assignment
    ADD CONSTRAINT fk_assignment_feature_flag FOREIGN KEY (feature_key) REFERENCES public.feature_flag(key);


--
-- Name: user_feature_assignment_history fk_assignment_history_feature; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_feature_assignment_history
    ADD CONSTRAINT fk_assignment_history_feature FOREIGN KEY (feature_key) REFERENCES public.feature_flag(key);


--
-- Name: user_feature_assignment_history fk_assignment_history_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_feature_assignment_history
    ADD CONSTRAINT fk_assignment_history_user FOREIGN KEY (user_id) REFERENCES public.user_account(id) ON DELETE CASCADE;


--
-- Name: document_analysis_report fk_document_analysis_report_document; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_analysis_report
    ADD CONSTRAINT fk_document_analysis_report_document FOREIGN KEY (document_id) REFERENCES public.document(id) ON DELETE SET NULL;


--
-- Name: document_ia_file_analysis fk_document_ia_file_analysis_file; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_ia_file_analysis
    ADD CONSTRAINT fk_document_ia_file_analysis_file FOREIGN KEY (file_id) REFERENCES public.file(id) ON DELETE CASCADE;


--
-- Name: file_metadata fk_file_metadata_file; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file_metadata
    ADD CONSTRAINT fk_file_metadata_file FOREIGN KEY (file_id) REFERENCES public.file(id) ON DELETE CASCADE;


--
-- Name: file fk_file_on_storage_file; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file
    ADD CONSTRAINT fk_file_on_storage_file FOREIGN KEY (preview_file_id) REFERENCES public.storage_file(id);


--
-- Name: apartment_sharing fk_pdf_dossier_file_on_storage_file; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.apartment_sharing
    ADD CONSTRAINT fk_pdf_dossier_file_on_storage_file FOREIGN KEY (pdf_dossier_file_id) REFERENCES public.storage_file(id);


--
-- Name: file fk_storage_file_id_on_storage_file; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file
    ADD CONSTRAINT fk_storage_file_id_on_storage_file FOREIGN KEY (storage_file_id) REFERENCES public.storage_file(id);


--
-- Name: watermark_document fk_storage_file_id_on_watermark_document_pdf_file_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.watermark_document
    ADD CONSTRAINT fk_storage_file_id_on_watermark_document_pdf_file_id FOREIGN KEY (pdf_file_id) REFERENCES public.storage_file(id);


--
-- Name: watermark_document_storage_file fk_storage_file_id_on_watermark_dsf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.watermark_document_storage_file
    ADD CONSTRAINT fk_storage_file_id_on_watermark_dsf FOREIGN KEY (storage_file_id) REFERENCES public.storage_file(id);


--
-- Name: storage_file fk_storagefile_on_encryption_key; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.storage_file
    ADD CONSTRAINT fk_storagefile_on_encryption_key FOREIGN KEY (encryption_key_id) REFERENCES public.encryption_key(id);


--
-- Name: user_feature_assignment fk_user_feature_assignment_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_feature_assignment
    ADD CONSTRAINT fk_user_feature_assignment_user FOREIGN KEY (user_id) REFERENCES public.user_account(id) ON DELETE CASCADE;


--
-- Name: watermark_document_storage_file fk_watermark_document_id_on_watermark_dsf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.watermark_document_storage_file
    ADD CONSTRAINT fk_watermark_document_id_on_watermark_dsf FOREIGN KEY (watermark_document_id) REFERENCES public.watermark_document(id);


--
-- Name: document fk_watermark_file_id_on_storage_file; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document
    ADD CONSTRAINT fk_watermark_file_id_on_storage_file FOREIGN KEY (watermark_file_id) REFERENCES public.storage_file(id);


--
-- Name: tenant fkbbp6xnxjdxtbm4oa376vq7kps; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant
    ADD CONSTRAINT fkbbp6xnxjdxtbm4oa376vq7kps FOREIGN KEY (apartment_sharing_id) REFERENCES public.apartment_sharing(id);


--
-- Name: tenant fkggy82nodwqietenfjj4e07f2p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant
    ADD CONSTRAINT fkggy82nodwqietenfjj4e07f2p FOREIGN KEY (id) REFERENCES public.user_account(id);


--
-- Name: property fkj2cohq7sjhdetbls088cupcu3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property
    ADD CONSTRAINT fkj2cohq7sjhdetbls088cupcu3 FOREIGN KEY (owner_id) REFERENCES public.owner(id);


--
-- Name: guarantor fkkjbk4iu5d5m170fbra4sf2l0m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guarantor
    ADD CONSTRAINT fkkjbk4iu5d5m170fbra4sf2l0m FOREIGN KEY (tenant_id) REFERENCES public.tenant(id);


--
-- Name: operator_log fkmphlbun7w9d0morfcbsc8dr8v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operator_log
    ADD CONSTRAINT fkmphlbun7w9d0morfcbsc8dr8v FOREIGN KEY (operator_id) REFERENCES public.user_account(id);


--
-- Name: property_apartment_sharing fkovnqm85cwx6lqole1tbh5nygl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_apartment_sharing
    ADD CONSTRAINT fkovnqm85cwx6lqole1tbh5nygl FOREIGN KEY (apartment_sharing_id) REFERENCES public.apartment_sharing(id);


--
-- Name: message fkowi205yn15gndgk65016dwabl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT fkowi205yn15gndgk65016dwabl FOREIGN KEY (from_user) REFERENCES public.user_account(id);


--
-- Name: bo_user fkq52lup1o33vbhtk3ccas5nslf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bo_user
    ADD CONSTRAINT fkq52lup1o33vbhtk3ccas5nslf FOREIGN KEY (id) REFERENCES public.user_account(id);


--
-- Name: owner fkqmm4qxh3yx65ya2k0ftj41j8b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.owner
    ADD CONSTRAINT fkqmm4qxh3yx65ya2k0ftj41j8b FOREIGN KEY (id) REFERENCES public.user_account(id);


--
-- Name: password_recovery_token password_recovery_token_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_recovery_token
    ADD CONSTRAINT password_recovery_token_fk FOREIGN KEY (user_id) REFERENCES public.user_account(id) ON DELETE CASCADE;


--
-- Name: tenant_userapi tenant_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant_userapi
    ADD CONSTRAINT tenant_id FOREIGN KEY (tenant_id) REFERENCES public.tenant(id);


--
-- Name: user_roles user_roles_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_fk FOREIGN KEY (user_id) REFERENCES public.user_account(id) ON DELETE CASCADE;


--
-- Name: tenant_userapi userapi_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant_userapi
    ADD CONSTRAINT userapi_id FOREIGN KEY (userapi_id) REFERENCES public.user_api(id);


--
-- PostgreSQL database dump complete
--

